### ISSUE TITLE
theme & theme-source parameters not functioning

### ISSUE THREAD

**Issue by pixDeVl** [Universal-Omega/PortableInfobox#106]
I have been attempting to use the theme and theme source arguments of the extension on my [Miraheze wiki](https://nyctocosm.miraheze.org/wiki/Template:Mobs/Sandbox), however, after saving, the wrapper maintains the `pi-theme-default` class(verified with inspect element).  
![image](https://github.com/Universal-Omega/PortableInfobox/assets/93949551/fc3a0bba-4880-4d5e-8c15-59b42a9148b4)
![image](https://github.com/Universal-Omega/PortableInfobox/assets/93949551/e407d2e8-913b-4821-a339-1dd3a632e9e8)
I have not been able to find any mention of this feature not being included in the documentation and see references to it in the repo code.

**Comment by alex4401** [comment]
You've linked Template:Mobs/Sandbox, which transcludes Template:Mob which does not have a theme set. Swapping out the transclusion to {{Mobs/Sandbox outputs correct theme classes for me.
![image](https://github.com/Universal-Omega/PortableInfobox/assets/33527044/9ff2ab09-d2a3-4e1b-82da-d5108a84036c)
