### ISSUE TITLE
Panel section labels (tabs) display raw HTML as text, like `<p>Label</p>`

### ISSUE THREAD

**Issue by TaylanUB** [Universal-Omega/PortableInfobox#115]
Please see the following page:

https://bg3.wiki/wiki/User:Taylan/InfoboxTestLabelBug

Here's the source, just for the sake of having it archived directly as part of this bug report:

```
<includeonly><infobox>
<title source="title"></title>
<panel>
  <section>
    <label>Section 1</label>
    <group>
      <header>Header for Section 1</header>
      <data source="s1v1">
        <label>Value Label 1</label>
      </data>
      <data source="s1v2">
        <label>Value Label 2</label>
      </data>
    </group>
  </section>
  <section>
    <label>Section 2</label>
    <group>
      <header>Header for Section 2</header>
      <data source="s2v1">
        <label>Value Label 1</label>
      </data>
      <data source="s2v2">
        <label>Value Label 2</label>
      </data>
    </group>
  </section>
</panel>
</infobox></includeonly><noinclude>
{{User:Taylan/InfoboxTestLabelBug
| title = Test
| s1v1 = S1 Value 1
| s1v2 = S1 Value 2
| s2v1 = S2 Value 1
| s2v2 = S2 Value 2
}}
</noinclude>
```

As you can see, the panel section labels are displayed as `<p>Section 1</p>` and `<p>Section 2</p>`. There seems to be too much escaping going on.

We're on the latest version of MediaWiki 1.39 and I'm on the REL1_39 branch of PortableInfobox.

https://bg3.wiki/wiki/Special:Version

**Comment by Universal-Omega** [comment]
Please set this in LocalSettings.php and see if it fixes the issue:
```php
$wgTidyConfig = [
	'driver' => 'RemexHtml',
	'pwrap' => false,
];
```

**Comment by TaylanUB** [comment]
Thanks for the quick response!

Hmm, is this going to have potentially unexpected effects over the entire wiki? The MediaWiki documentation for [$wgTidyConfig](https://www.mediawiki.org/wiki/Manual:$wgTidyConfig) doesn't make it clear to me what effects this may have. The `pwrap` option isn't mentioned at all unfortunately.

I'll enable it and see if I notice anything immediately wrong with some of our other pages, but I fear that it may cause some changes in HTML output that negatively affect a small number of pages on the wiki and may therefore go unnoticed for a while.

**Comment by TaylanUB** [comment]
It did fix the issue.

It indeed seems to cause subtle changes in some pages. I've only been able to find one change from a quick glance, which is that the contents of `<blockquote>` aren't wrapped in a `<p>` anymore. I guess there will be some other differences like this, where content previously wrapped in `<p>` will now appear bare instaed, but I think I'll leave the option enabled and hope for the best. We can always selectively re-wrap things in `<p>` in the page's source if we really want that in certain places.

I'm a little worried that we may have some CSS here and there that depends on some things being wrapped in a `<p>`, but it should be fine...

**Comment by Universal-Omega** [comment]
@TaylanUB Appreciate the confirmation. #116 should actually remove the need to set `$wgTidyConfig`
