### ISSUE TITLE
Improve PortableInfoboxBuilder browser support

### ISSUE THREAD

**Issue by Universal-Omega** [Universal-Omega/PortableInfobox#57]
Currently, per some user reports, for some unknown reason it is incompatible with Firefox and other browsers.

Browser version with verified incompatibilites: Firefox 96.0.3 on Arch Linux

```xsl
<transformiix:result xmlns:transformiix="http://www.mozilla.org/TransforMiix"><title source="title"><default>TestingFirefox</default></title><image source="image"/></transformiix:result> 
```
Is what the builder generates, filling the template with that raw output.

**Comment by SlidingHorn** [comment]
Feel free to tag me if there's more information I can provide or testing that needs done.

**Comment by Universal-Omega** [comment]
Something like this _might_ work:
```js
Node.prototype.transformNode = function ( xslDom ) {
	var processor = new XSLTProcessor();
	processor.importStylesheet( xslDom );

	var resultDom = processor.transformToDocument( this );
	var result = resultDom.xml;
	if ( result.indexOf( '<transformiix:result' ) > -1 ) {
		result = result.substring( result.indexOf( '>' ) + 1, result.lastIndexOf( '<' ) );
	}

	return result;
};
```

I will run some tests in a few days to see, and if so will implement something similar.
