### ISSUE TITLE
With the most recent update, MediaWiki seems to add paragraph tags in the PortableInfobox

### ISSUE THREAD

**Issue by seelentau** [Universal-Omega/PortableInfobox#81]
Hi, I was advised to post this here by the MediaWiki Discord. Sorry if it's incorrect, never used Github before^^

I have a problem with the portable infoboxes in my wiki, after finally updating it to the current version.

These p-tags appeared and I don't know where they come from:
![unknown](https://user-images.githubusercontent.com/106251398/171269620-791ea299-7c73-410d-a316-904877b07507.png)

this is my commons.css: https://degwiki.com/wiki/MediaWiki:Common.css
I tried outcommenting all the CSS for the infobox in question, but that didn't fix it

and this is the template for the infobox: https://degwiki.com/wiki/Template:Release

here you can see what it looked like pre-update: https://web.archive.org/web/20210618215104/https://degwiki.com/wiki/The_Insulated_World_(2018)

Update: the server owner who hosts my wiki figured out a way around this via some "dirty fix", he says.
But the problem itself still remains - there are paragraph tags that weren't there in the old version:

pre-update:
`<h2 class="pi-item pi-item-spacing pi-title" data-source="title">鬼葬</h2>`

post-update:
`<h2 class="pi-item pi-item-spacing pi-title" data-source="title"><p>鬼葬</p></h2>`

**Comment by Universal-Omega** [comment]
Hi, please try to set the following:
```php
$wgTidyConfig = [
	'driver' => 'RemexHtml',
	'pwrap' => false,
];
```
Please let me know if it works. Thanks!

**Comment by seelentau** [comment]
Hi, thanks for the quick fix, it appears to have worked.

However, quoting the server owner, they say:
"that piece of code seems like it’s telling the HTML parser not to insert paragraph tags anywhere"

I haven't noticed any discrepancies in relation to that yet, just wanted to note it for future reference.
