### ISSUE TITLE
Horizontal groups do not align properly in MediaWiki 1.39

### ISSUE THREAD

**Issue by the-dragons-studio** [Universal-Omega/PortableInfobox#91]
Spun off from issue #89, this bug concerns the fact that horizontal groups are broken. Normally, the contents of parallel horizontal groups are meant to be neatly stacked side by side, but as of 1.39, they are clustered top to bottom, in a broken manner, reducing readability and looking off-putting to readers. This is demonstrated in the below screenshot. Note that I used Vector 2022 for this screenshot, but I tested five skins; Cosmos, Refreshed, Vector, MonoBook and Timeless and all demonstrate the broken infobox behaviour.
![image](https://user-images.githubusercontent.com/62834738/206119196-c06ea398-f39a-4227-8123-ddd690ad4f96.png)

**Comment by SavageAlien** [comment]
It's related to CSS changes [in this commit](https://github.com/Universal-Omega/PortableInfobox/commit/a5f82d1bfbc91a2dc765e1b2cd9e5fe995145c0c) .

Adding `flex` has a side effect of ruining the layout for data in horizontal-groups - As demonstrated in your screenshot.
And also the `align-items: center;` messes with things like `<sup>` (superscripted) text like References which are meant to display in top corners of text.
